import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import type { Task, Team } from '../db/schemas';
import { format } from 'date-fns';

interface ExportData {
    tasks: Task[];
    teams: Team[];
    userName: string;
    dateRange?: { start: Date; end: Date };
}

// Generate PDF Report
export const generatePDFReport = (data: ExportData): void => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Title
    doc.setFontSize(20);
    doc.text('TeamOps Report', pageWidth / 2, 20, { align: 'center' });

    // Subtitle
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated by ${data.userName} on ${format(new Date(), 'PPP')}`, pageWidth / 2, 28, { align: 'center' });

    // Stats Summary
    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text('Summary', 14, 40);

    const totalTasks = data.tasks.length;
    const completedTasks = data.tasks.filter(t => t.status === 'done').length;
    const inProgressTasks = data.tasks.filter(t => t.status === 'in-progress').length;
    const todoTasks = data.tasks.filter(t => t.status === 'todo').length;
    const highPriority = data.tasks.filter(t => t.priority === 'high').length;

    doc.setFontSize(10);
    const summaryY = 48;
    doc.text(`Total Teams: ${data.teams.length}`, 14, summaryY);
    doc.text(`Total Tasks: ${totalTasks}`, 14, summaryY + 6);
    doc.text(`Completed: ${completedTasks} (${totalTasks ? Math.round(completedTasks / totalTasks * 100) : 0}%)`, 14, summaryY + 12);
    doc.text(`In Progress: ${inProgressTasks}`, 80, summaryY + 6);
    doc.text(`To Do: ${todoTasks}`, 80, summaryY + 12);
    doc.text(`High Priority: ${highPriority}`, 140, summaryY + 6);

    // Tasks Table
    doc.setFontSize(14);
    doc.text('Tasks', 14, summaryY + 28);

    const taskRows = data.tasks.map(task => [
        task.title.substring(0, 30) + (task.title.length > 30 ? '...' : ''),
        task.status,
        task.priority || 'medium',
        task.deadline ? format(new Date(task.deadline), 'MMM d, yyyy') : '-',
        task.completedAt ? 'Yes' : 'No'
    ]);

    autoTable(doc, {
        startY: summaryY + 32,
        head: [['Title', 'Status', 'Priority', 'Deadline', 'Completed']],
        body: taskRows,
        styles: { fontSize: 8 },
        headStyles: { fillColor: [59, 130, 246] },
    });

    // Teams Section
    const finalY = (doc as any).lastAutoTable?.finalY || summaryY + 60;

    if (finalY < 250) {
        doc.setFontSize(14);
        doc.text('Teams', 14, finalY + 14);

        const teamRows = data.teams.map(team => [
            team.name,
            team.members.length.toString(),
            format(new Date(team.createdAt), 'MMM d, yyyy')
        ]);

        autoTable(doc, {
            startY: finalY + 18,
            head: [['Team Name', 'Members', 'Created']],
            body: teamRows,
            styles: { fontSize: 8 },
            headStyles: { fillColor: [34, 197, 94] },
        });
    }

    // Save
    doc.save(`teamops-report-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
};

// Generate Excel Report
export const generateExcelReport = (data: ExportData): void => {
    const workbook = XLSX.utils.book_new();

    // Summary Sheet
    const summaryData = [
        ['TeamOps Report'],
        ['Generated:', format(new Date(), 'PPP')],
        ['User:', data.userName],
        [''],
        ['Summary'],
        ['Total Teams', data.teams.length],
        ['Total Tasks', data.tasks.length],
        ['Completed Tasks', data.tasks.filter(t => t.status === 'done').length],
        ['In Progress', data.tasks.filter(t => t.status === 'in-progress').length],
        ['To Do', data.tasks.filter(t => t.status === 'todo').length],
        ['High Priority', data.tasks.filter(t => t.priority === 'high').length],
    ];
    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');

    // Tasks Sheet
    const taskHeaders = ['Title', 'Description', 'Status', 'Priority', 'Deadline', 'Completed At', 'Created At'];
    const taskData = data.tasks.map(task => [
        task.title,
        task.description || '',
        task.status,
        task.priority || 'medium',
        task.deadline ? format(new Date(task.deadline), 'yyyy-MM-dd') : '',
        task.completedAt ? format(new Date(task.completedAt), 'yyyy-MM-dd') : '',
        format(new Date(task.createdAt), 'yyyy-MM-dd')
    ]);
    const tasksSheet = XLSX.utils.aoa_to_sheet([taskHeaders, ...taskData]);
    XLSX.utils.book_append_sheet(workbook, tasksSheet, 'Tasks');

    // Teams Sheet
    const teamHeaders = ['Name', 'Description', 'Members Count', 'Created At'];
    const teamData = data.teams.map(team => [
        team.name,
        team.description || '',
        team.members.length,
        format(new Date(team.createdAt), 'yyyy-MM-dd')
    ]);
    const teamsSheet = XLSX.utils.aoa_to_sheet([teamHeaders, ...teamData]);
    XLSX.utils.book_append_sheet(workbook, teamsSheet, 'Teams');

    // Save
    XLSX.writeFile(workbook, `teamops-report-${format(new Date(), 'yyyy-MM-dd')}.xlsx`);
};
